### ISSUE TITLE
"Complete Setup" doesn't work -> version `GLIBC_2.34' not found

### ISSUE THREAD

**Issue by goreil** [shellphish/how2heap#178]
When following the `Complete-Setup` guide to setup a docker environment, it produces the following error:

When attempting to run `./glibc_run.sh 2.30 ./malloc_playground -u -r` or just `./malloc_playground` it returns: version `GLIBC_2.34' not found, same as Issue #169

The issue here is that we are using the `Dockerfile` from https://github.com/pwndbg/pwndbg which in turn uses `ubuntu:22.04`.

# Workaround
After the command `git clone https://github.com/pwndbg/pwndbg` edit `pwndbg/Dockerfile` and replace `jammy` (ubuntu 22.04) with `focal` (ubuntu 20.04)

```
-ARG image=mcr.microsoft.com/devcontainers/base:jammy
+ARG image=mcr.microsoft.com/devcontainers/base:focal
```

**Comment by Kyle-Kyle** [comment]
it is fixed in the latest commit https://github.com/shellphish/how2heap/commit/8e4af70029a4d017a425cf0ea8e056f682cc9425
please let me know if you still encounter any issues.
And thank you for letting me know the issue.

**Comment by Kyle-Kyle** [comment]
you should be able to just `./glibc_run.sh <libc_version> <binary> -d` to launch the target binary in the target glibc

**Comment by goreil** [comment]
Hi @Kyle-Kyle ! Thank you for the quick fix!

However after testing it on Ubuntu 22.04 I noticed a few issues:
1.`../glibc_run.sh 2.30 ./malloc_playground -d -p` does not actually link the correct libc now:
```
ldd ./malloc_playground
	[...]
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (system libc instead of ./glibc_versions/2.30/x64/lib/ld-2.30.so)
```
2. `pwndbg` is no longer included in the complete setup.


I would like to work on this by creating a new `Dockerfile` that includes `pwndbg` and fixes the afformentioned issues. Does that work for you?

**Comment by Kyle-Kyle** [comment]
I'm a bit confused about how you are using it. Are you using it inside the docker container?
In the latest complete setup, it is the binary on the host that's supposed to be patched to use custom glibc.
Installing pwndbg is not part of the workflow anymore (pwndbg was installed in the docker container, since you don't need to work inside the container now, you don't need to install pwndbg inside it)

**Comment by goreil** [comment]
While the current setup works, it requires a few additional steps that are not immediatly described in the `README.md`.

While I understand that the target audience are tech-savvy hackers, I nonetheless believe a simple setup, as the previous setup with Docker before https://github.com/shellphish/how2heap/commit/8e4af70029a4d017a425cf0ea8e056f682cc9425
will be quite helpful.

As a proposal, I created  a pull request #179 , but I'm open to discussion.

**Comment by goreil** [comment]
Hi please don't take this the wrong way. I love this repository and it has helped me a lot in understanding heap exploitation. 

I want to contribute by creating a docker setup that works out of the box with additional tools like `pwntools` and `pwndbg` included.

**Comment by Kyle-Kyle** [comment]
> Hi please don't take this the wrong way.

Definitely not. I was just not sure why the patch didn't solve the issue.
And thank you for figuring out the issue. I'll update the README for now and wait for your PR to the Makefile :)

**Comment by Kyle-Kyle** [comment]
I double-checked. You are right. It doesn't work in a fresh installation. I just created a quick patch. Can you please check whether it works for you? https://github.com/shellphish/how2heap/tree/fix/complete_setup

The reason why I am against including pwndbg in the Dockerfile in this project is that it should be in a tool-neural way so that people can choose to use their favorite heap debugging tool to learn these. instead of bound to pwndbg.

**Comment by goreil** [comment]
Your patch (https://github.com/shellphish/how2heap/tree/fix/complete_setup) works on my machine. Thank you!

I understand your reasoning for excluding pwndbg. I'll close the pull request. 

As far as I'm concerned this issue will be solved with your new patche and can be closed when the patch is applied.
