### ISSUE TITLE
house_of_einherjar example size check

### ISSUE THREAD

**Issue by bannsec** [shellphish/how2heap#34]
I'm seeing the following in the example posted:

> We edit our fake chunk size so that it is small enough to pass size checks

Can you guys post a url (maybe in the code) to where in the C code this check is taking place?

**Comment by andigena** [comment]
Now I haven't stepped through the example but I believe it's referring to the size check against `av->system_mem` in the binning code in `_int_malloc`, since after the consolidation the size of the fake chunk would be huge and we would abort [here](https://code.woboq.org/userspace/glibc/malloc/malloc.c.html#3474).

**Comment by DhavalKapil** [comment]
@andigena is correct. If the `fake_chunk` does not end up as the new top chunk(because of `c`), it'll end up in 'unsorted' bin. Chunks from unsorted bin will be checked as mentioned above ^.

Also, a recent [commit](http://repo.or.cz/glibc.git/commitdiff/17f487b7afa7cd6c316040f3e6c86dc96b2eec30)(18th March 2017) adds another check in `unlink` for the size of the chunk being unlinked. The `size`(with masked `SIZE_BITS`) should match the next chunk's `prev_size`. A modification is required for the 'House of  Einherjar' to work for future versions of glibc.

**Comment by m1ghtym0** [comment]
The mentioned line has since been replaced with a better description. Also a bypass for the new check @DhavalKapil mentioned was introduced.
@zardus Guess you can close this one as well

**Comment by zardus** [comment]
:+1:
